#!/usr/bin/env bash
# Scaffold a new host in this repo, ready to install.
#
# Normally run from a NixOS installer USB booted on the new machine itself.
# (It also works from any machine with Nix if you're driving a remote install
# with nixos-anywhere — see README.md.)
#
# Usage: scripts/new-host.sh <new-hostname>
#
# This only sets up the two things that can't be shared between machines:
#   - Which disk to install to (you supply this; nothing auto-detects it,
#     and getting it wrong wipes the wrong drive)
#   - A placeholder hardware-configuration.nix, so the flake still evaluates
#     before the real one has been generated
#
# It deliberately does NOT partition, install, or touch any disk — it only
# writes files into this repo. The commands it prints at the end do the
# actual work, so you can read them before anything destructive happens.

set -euo pipefail

if [ $# -ne 1 ]; then
  echo "Usage: $0 <new-hostname>" >&2
  exit 1
fi

HOST="$1"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TEMPLATE_DIR="$REPO_ROOT/hosts/thinkpad"
HOST_DIR="$REPO_ROOT/hosts/$HOST"

if [ -e "$HOST_DIR" ]; then
  echo "hosts/$HOST already exists — pick a different name, or remove it first." >&2
  exit 1
fi

cat <<'PROMPT'
List the disks on the machine being installed:

    ls -l /dev/disk/by-id/

Pick the whole-disk entry for the drive you want to install to — NOT a
partition (ignore anything ending in -part1, -part2, ...). It will look
something like:

    nvme-SAMSUNG_MZVL2512HCJQ_S64KNX0T123456
    ata-Samsung_SSD_870_EVO_500GB_S6PENL0T900001

Use the by-id name rather than /dev/sda or /dev/nvme0n1: this is the disk
that gets WIPED, and kernel names can shift between boots.

PROMPT

read -rp "Target disk by-id name: " DISK_ID

if [ -z "$DISK_ID" ]; then
  echo "No disk given — aborting, nothing was changed." >&2
  exit 1
fi

case "$DISK_ID" in
  *-part[0-9]*)
    echo "That looks like a partition, not a whole disk — aborting." >&2
    exit 1
    ;;
  /dev/*)
    echo "Enter just the by-id name, without the /dev/disk/by-id/ prefix." >&2
    exit 1
    ;;
esac

DISK_PATH="/dev/disk/by-id/$DISK_ID"

echo
echo "!! ALL DATA on $DISK_PATH will be DESTROYED when you run disko. !!"
echo "   (This script only writes config files — nothing is wiped yet.)"
read -rp "Type the disk name again to confirm: " CONFIRM
if [ "$CONFIRM" != "$DISK_ID" ]; then
  echo "Confirmation did not match — aborting, nothing was changed." >&2
  exit 1
fi

mkdir -p "$HOST_DIR"
cp "$TEMPLATE_DIR/configuration.nix" "$HOST_DIR/configuration.nix"
cp "$TEMPLATE_DIR/disk-config.nix" "$HOST_DIR/disk-config.nix"

sed -i "s/networking.hostName = \"[^\"]*\";/networking.hostName = \"$HOST\";/" "$HOST_DIR/configuration.nix"
sed -i "s#device = \"[^\"]*\";#device = \"$DISK_PATH\";#" "$HOST_DIR/disk-config.nix"

# system.stateVersion is intentionally inherited from the template: it should
# match the nixpkgs release this flake installs (nixos-26.05), not whatever
# release the machine running this script happens to be on.

cat > "$HOST_DIR/hardware-configuration.nix" <<'EOF'
# Placeholder. Replaced during install with this machine's real hardware
# config, generated by nixos-generate-config (see the steps printed by
# scripts/new-host.sh). Don't write this by hand.
#
# It has to exist, and be git-tracked, before installing: the flake imports
# it, and Nix ignores files git doesn't know about.
{ }
EOF

cat <<EOF

Created hosts/$HOST (hostname + target disk recorded).

Next steps — run these on this machine. Step 2 ERASES $DISK_PATH.
If nix complains about experimental features, add:
  --extra-experimental-features 'nix-command flakes'

  1. Double-check the disk is the one you meant:
       grep device "$HOST_DIR/disk-config.nix"

  2. Partition, format and mount it (DESTRUCTIVE):
       sudo nix run github:nix-community/disko -- \\
         --mode destroy,format,mount "$HOST_DIR/disk-config.nix"

  3. Generate this machine's real hardware config, replacing the
     placeholder (--no-filesystems because disko already defines them):
       sudo nixos-generate-config --no-filesystems --root /mnt
       cp /mnt/etc/nixos/hardware-configuration.nix "$HOST_DIR/"

  4. Make the new files visible to Nix (it ignores untracked files):
       git -C "$REPO_ROOT" add -A

  5. Install:
       sudo nixos-install --root /mnt --flake "$REPO_ROOT#$HOST"

  6. Reboot, then log in at the console with the bootstrap password from
     modules/common.nix and secure the machine:
       passwd                 # set your real password
       nmtui                  # connect WiFi, if not on ethernet

  7. Commit and push hosts/$HOST/ — including the generated
     hardware-configuration.nix, which is what makes this machine
     reproducible later.

Installing onto a headless box you can't sit at? See the nixos-anywhere
section in README.md instead.
EOF
