#!/usr/bin/env bash
# Scaffold a new host in this repo, ready to install.
#
# Run this on the new machine, booted from a NixOS installer USB, after
# cloning this repo onto it. See the "Installing on a new machine" section
# of README.md for the full walkthrough.
#
# Usage: scripts/new-host.sh <new-hostname>
#
# This sets up the pieces that can't be shared between machines:
#   - Which disk to install to (you supply this; nothing auto-detects it,
#     and naming the wrong one wipes the wrong drive)
#   - The hostname
#   - A placeholder hardware-configuration.nix, so the flake still evaluates
#     before the real one has been generated
#
# It deliberately does NOT partition, format, or install anything — it only
# writes files into this repo. The commands it prints at the end do the real
# work, so you can read them before anything destructive happens.

set -euo pipefail

if [ $# -ne 1 ]; then
  echo "Usage: $0 <new-hostname>" >&2
  exit 1
fi

HOST="$1"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TEMPLATE_DIR="$REPO_ROOT/hosts/thinkpad"
HOST_DIR="$REPO_ROOT/hosts/$HOST"

if [ -e "$HOST_DIR" ]; then
  echo "hosts/$HOST already exists — pick a different name, or remove it first." >&2
  exit 1
fi

cat <<'PROMPT'
List the disks on this machine:

    ls -l /dev/disk/by-id/

Pick the whole-disk entry for the drive you want to install to — NOT a
partition (ignore anything ending in -part1, -part2, ...). It will look
something like:

    nvme-SAMSUNG_MZVL2512HCJQ_S64KNX0T123456
    ata-Samsung_SSD_870_EVO_500GB_S6PENL0T900001

Use the by-id name rather than /dev/sda or /dev/nvme0n1: this is the disk
that gets wiped, and kernel names can shift between boots.

PROMPT

read -rp "Disk by-id name: " DISK_ID

if [ -z "$DISK_ID" ]; then
  echo "No disk given — aborting, nothing was changed." >&2
  exit 1
fi

case "$DISK_ID" in
  *-part[0-9]*)
    echo "That looks like a partition, not a whole disk — aborting." >&2
    exit 1
    ;;
  /dev/*)
    echo "Enter just the by-id name, without the /dev/disk/by-id/ prefix." >&2
    exit 1
    ;;
esac

DISK_PATH="/dev/disk/by-id/$DISK_ID"

if [ ! -e "$DISK_PATH" ]; then
  echo
  echo "Warning: $DISK_PATH doesn't exist on this machine."
  echo "That's expected if you're preparing the config elsewhere, but a typo"
  echo "here means the install will fail (or wipe the wrong disk)."
  read -rp "Continue anyway? [y/N] " PROCEED
  case "$PROCEED" in
    [yY]*) ;;
    *) echo "Aborting, nothing was changed." >&2; exit 1 ;;
  esac
fi

echo
echo "!! ALL DATA on $DISK_PATH will be DESTROYED when you run disko. !!"
echo "   (This script only writes config files — nothing is wiped yet.)"
read -rp "Type the disk name again to confirm: " CONFIRM
if [ "$CONFIRM" != "$DISK_ID" ]; then
  echo "Confirmation did not match — aborting, nothing was changed." >&2
  exit 1
fi

mkdir -p "$HOST_DIR"
cp "$TEMPLATE_DIR/configuration.nix" "$HOST_DIR/configuration.nix"
cp "$TEMPLATE_DIR/disk-config.nix" "$HOST_DIR/disk-config.nix"

sed -i "s/networking.hostName = \"[^\"]*\";/networking.hostName = \"$HOST\";/" "$HOST_DIR/configuration.nix"
sed -i "s#device = \"[^\"]*\";#device = \"$DISK_PATH\";#" "$HOST_DIR/disk-config.nix"

# system.stateVersion is intentionally inherited from the template: it should
# match the nixpkgs release this flake installs (nixos-26.05), not whatever
# release the installer USB happens to be.

cat > "$HOST_DIR/hardware-configuration.nix" <<'EOF'
# Placeholder. Replaced during install with this machine's real hardware
# config, generated by nixos-generate-config (see the steps printed by
# scripts/new-host.sh). Don't write this by hand.
#
# It has to exist, and be git-tracked, before installing: the flake imports
# it, and Nix ignores files git doesn't know about.
{ }
EOF

cat <<EOF

Created hosts/$HOST:
  hostname : $HOST
  disk     : $DISK_PATH

Next steps. Step 2 ERASES that disk. If nix complains about experimental
features, add: --extra-experimental-features 'nix-command flakes'

  1. Confirm the disk is the one you meant:
       grep device "$HOST_DIR/disk-config.nix"

  2. Partition, format and mount it (DESTRUCTIVE):
       sudo nix run github:nix-community/disko -- \\
         --mode destroy,format,mount "$HOST_DIR/disk-config.nix"

  3. Generate this machine's real hardware config, overwriting the
     placeholder (--no-filesystems because disko already declares them):
       sudo nixos-generate-config --no-filesystems --show-hardware-config \\
         > "$HOST_DIR/hardware-configuration.nix"

  4. Stage the new files — Nix ignores anything git doesn't know about:
       git -C "$REPO_ROOT" add -A

  5. Install (prompts for a root password at the end):
       sudo nixos-install --root /mnt --flake "$REPO_ROOT#$HOST"

  6. Reboot, remove the USB, and log in as joe with the bootstrap password
     from modules/common.nix. Then straight away:
       passwd                 # set your real password
       nmtui                  # connect WiFi, if not on ethernet

  7. Commit and push hosts/$HOST/ — including the generated
     hardware-configuration.nix, which is what makes this machine
     reproducible later.
EOF
